FROM golang:1.23.1 AS build-stage

WORKDIR /app

COPY go.mod go.sum ./
COPY *.go ./

RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux go build -o ./server

# Run the tests in the container
FROM build-stage AS run-test-stage
RUN go test -v ./...

# Deploy the application binary into a lean image
FROM gcr.io/distroless/base-debian11 AS build-release-stage

WORKDIR /

COPY --from=build-stage /app/server /server

EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT ["/server"]